#! /bin/sh

MAX_UPLOAD_SIZE=8M

######## Create /var/lib/derbynet directory, for storing race information

mkdir -m 777 /var/lib/derbynet 2>/dev/null || true

######## Create local directory, point to /var/lib/derbynet

mkdir -m 777 /var/www/html/derbynet/local 2>/dev/null || true

cat <<EOF >/var/www/html/derbynet/local/default-file-path.inc
<?php
\$default_file_path = "/var/lib/derbynet";
?>
EOF

######## PHP config

sed -i.pre-derbynet -e "s/^upload_max_filesize = 2M/upload_max_filesize = $MAX_UPLOAD_SIZE/" /etc/php5/fpm/php.ini
echo Restarting php5-fpm
service php5-fpm restart

######### Add derbynet location clause if not already there

grep derbynet /etc/nginx/sites-available/default >/dev/null 2>&1 || \
sed -i -e '/^[ \t]*location \/ {/ i\
\tinclude derbynet/location.snippet; \

' /etc/nginx/sites-available/default

######## Restart

nginx -s reload
