#! /bin/bash

BASE_URL=$1
set -e -E -o pipefail

if [ "$BASE_URL" = "" ]; then
	echo Base URL required!
	exit
fi

if [ "$2" = "" ]; then
    echo "Usage: <URL root> \"action=xyz&param1=...\""
    exit
fi

source `dirname $0`/common.sh

curl_postj action.php "$2"
