#! /bin/bash

BASE_URL=$1
set -e -E -o pipefail
source `dirname $0`/common.sh

curl_postj action.php "action=racer.pass&racer=1&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=2&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=3&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=4&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=5&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=6&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=7&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=8&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=9&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=10&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=11&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=12&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=13&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=14&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=15&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=16&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=17&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=18&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=19&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=20&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=21&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=22&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=23&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=24&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=25&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=26&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=27&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=28&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=29&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=30&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=31&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=32&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=33&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=34&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=35&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=36&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=37&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=38&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=39&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=40&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=41&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=42&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=43&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=44&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=45&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=46&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=47&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=48&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=49&value=1" | check_jsuccess

curl_postj action.php "action=racer.pass&racer=50&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=51&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=52&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=53&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=54&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=55&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=56&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=57&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=58&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=59&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=60&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=61&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=62&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=63&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=64&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=65&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=66&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=67&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=68&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=69&value=1" | check_jsuccess

curl_postj action.php "action=racer.pass&racer=70&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=71&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=72&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=73&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=74&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=75&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=76&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=77&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=78&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=79&value=1" | check_jsuccess

curl_postj action.php "action=racer.pass&racer=80&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=81&value=1" | check_jsuccess
curl_postj action.php "action=racer.pass&racer=82&value=1" | check_jsuccess
