#! /bin/bash

BASE_URL=$1
set -e -E -o pipefail

NOANNOUNCE=1
source `dirname $0`/common.sh

if [ "$2" = "" ]; then
    echo "Usage: <URL root> \"query=xyz&param1=...\""
    exit
fi

curl_getj "action.php?$2"
