/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jeffpiazza.derby.gui;

import org.junit.Test;

import java.io.File;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class IconResourceTest {
    /**
     * This test makes sure that the Gradle build script copies the icons and that all of the icons
     * in the IconResource enum point to valid paths
     *
     * @throws URISyntaxException
     */
    @Test
    public void shouldFindAllIconResources() throws URISyntaxException {
        for (IconResource value : IconResource.values()) {
            URL url = getClass().getResource(value.getPath());
            File file = Paths.get(url.toURI()).toFile();
            assertThat(file.exists(), is(true));
        }
    }
}
