<?php
return array(
  "INSERT INTO AwardTypes (AwardTypeID, AwardType) VALUES (1, 'Design General')",
  "INSERT INTO AwardTypes (AwardTypeID, AwardType) VALUES (2, 'Speed General')",
  "INSERT INTO AwardTypes (AwardTypeID, AwardType) VALUES (3, 'Other')",
  "INSERT INTO AwardTypes (AwardTypeID, AwardType) VALUES (4, 'Design Trophy')",
  "INSERT INTO AwardTypes (AwardTypeID, AwardType) VALUES (5, 'Speed Trophy')",
  "INSERT INTO AwardTypes (AwardTypeID, AwardType) VALUES (6, 'Ad Hoc')",
);
?>