#! /bin/sh

MAX_UPLOAD_SIZE=16M

if [ -f /etc/os-release ] ; then
    . /etc/os-release
elif [ -f /usr/lib/os-release ] ; then
    . /usr/lib/os-release
else
    ID=linux
fi

######## Create /var/lib/derbynet directory, for storing race information

mkdir -m 777 /var/lib/derbynet         2>/dev/null || true
mkdir -m 777 /var/lib/derbynet/imagery 2>/dev/null || true
mkdir -m 777 /var/lib/derbynet/slides  2>/dev/null || true

######## Create local directory, point to /var/lib/derbynet

mkdir -m 777 /var/www/html/derbynet/local 2>/dev/null || true

# V2.0 didn't include JUDGING_PERMISSION for race crew in the default
# config-roles file.  Delete and recreate the config-roles file.
test -e /var/www/html/derbynet/local/config-roles.inc && \
grep -q -v JUDGING_PERMISSION /var/www/html/derbynet/local/config-roles.inc && \
    sed -i.bak -e 's/ASSIGN_RACER_IMAGE_PERMISSION/ASSIGN_RACER_IMAGE_PERMISSION | JUDGING_PERMISSION/' \
        /var/www/html/derbynet/local/config-roles.inc

######## PHP config

# How large are the pictures you want to upload?  8M covers an 18-megapixel
# photo.
MAX_UPLOAD_SIZE=16M

if [ -e /etc/php5 ] ; then
    sed -i.pre-derbynet -e "s/^upload_max_filesize = [28]M/upload_max_filesize = $MAX_UPLOAD_SIZE/" \
        -e "s#^post_max_size = [2-8]M#post_max_size = $MAX_UPLOAD_SIZE#" \
        /etc/php5/fpm/php.ini
    echo Restarting php5-fpm
    service php5-fpm restart
fi
for INI in `find /etc/php -name php.ini` ; do
    sed -i.pre-derbynet \
    -e "s#^upload_max_filesize = [28]M#upload_max_filesize = $MAX_UPLOAD_SIZE#" \
    -e "s#^post_max_size = [2-8]M#post_max_size = $MAX_UPLOAD_SIZE#" \
    -e "s#^memory_limit = 128M#memory_limit = 256M#" \
    -e "s#^session.gc_maxlifetime = 1440#session.gc_maxlifetime = 28800#" \
        $INI
done
for SVC in  `find /etc/init.d -name php\* -exec basename {} \;` ; do
    echo Restarting $SVC
    service $SVC restart
done


######### Update derbynet location snippet to match PHP version

VAR_RUN=`readlink /var/run`
if [ -e /var/run/php-fpm.sock ] ; then
    SOCKET=/var/run/php-fpm.sock
else
    # If two different PHP versions installed, the 'find' might come up with two
    # candidates; 'tail' picks the last one.
    SOCKET=`find "$VAR_RUN" -name \*fpm.sock | tail -n 1`
fi
sed -i -e"s#/var/run/php5-fpm.sock#$SOCKET#" /etc/nginx/derbynet/location.snippet

######### Add derbynet location clause if not already there

grep derbynet /etc/nginx/sites-available/default >/dev/null 2>&1 || \
sed -i -e '/^[ \t]*location \/ {/ i\
\tinclude derbynet/location.snippet; \

' /etc/nginx/sites-available/default

######## Enable SSL with self-signed ("snakeoil") certificates provided by ssl-cert package

sed -i \
    -e 's!# *\(listen 443 ssl .*\)!\1!' \
	-e 's!# *\(listen [::]:443 ssl .*\)!\1!' \
    -e 's!# *\(include snippets/snakeoil.conf;\)!\1!' \
    /etc/nginx/sites-available/default

######## Restart

nginx -s reload
