package org.jeffpiazza.derby.gui;


public class Components extends javax.swing.JFrame {

  /**
   * Creates new form NewJFrame
   */
  public Components() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    httpPanel = new javax.swing.JPanel();
    urlLabel = new javax.swing.JLabel();
    urlField = new javax.swing.JTextField();
    roleLabel = new javax.swing.JLabel();
    roleComboBox = new javax.swing.JComboBox<>();
    passwordLabel = new javax.swing.JLabel();
    passwordField = new javax.swing.JPasswordField();
    connectButton = new javax.swing.JButton();
    httpStatusLabel = new javax.swing.JLabel();
    httpIconStatusPanel = new javax.swing.JPanel();
    httpIconStatus = new javax.swing.JLabel();
    serialPanel = new javax.swing.JPanel();
    serialPanelBody = new javax.swing.JPanel();
    portScrollPane = new javax.swing.JScrollPane();
    portList = new javax.swing.JList<>();
    timerClassScrollPane = new javax.swing.JScrollPane();
    timerClassList = new javax.swing.JList<>();
    scanButton = new javax.swing.JButton();
    serialStatusLabel = new javax.swing.JLabel();
    serialIconStatusPanel = new javax.swing.JPanel();
    serialIconStatus = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridLayout(1, 2));

    httpPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Server Connection"));

    urlLabel.setText("Server URL");

    roleLabel.setText("Role");

    roleComboBox.setEnabled(false);

    passwordLabel.setText("Password");

    passwordField.setEnabled(false);

    connectButton.setText("Connect");

    httpStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    httpStatusLabel.setText("Please enter server address");

    httpIconStatusPanel.setLayout(new javax.swing.BoxLayout(httpIconStatusPanel, javax.swing.BoxLayout.X_AXIS));

    httpIconStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    httpIconStatus.setPreferredSize(new java.awt.Dimension(60, 60));
    httpIconStatusPanel.add(httpIconStatus);

    javax.swing.GroupLayout httpPanelLayout = new javax.swing.GroupLayout(httpPanel);
    httpPanel.setLayout(httpPanelLayout);
    httpPanelLayout.setHorizontalGroup(
      httpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(urlField, javax.swing.GroupLayout.Alignment.TRAILING)
      .addComponent(passwordField)
      .addComponent(roleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(httpPanelLayout.createSequentialGroup()
        .addGroup(httpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(httpPanelLayout.createSequentialGroup()
            .addGroup(httpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(urlLabel)
              .addComponent(passwordLabel)
              .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(httpStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        .addContainerGap())
      .addComponent(connectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, httpPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(httpIconStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    httpPanelLayout.setVerticalGroup(
      httpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(httpPanelLayout.createSequentialGroup()
        .addComponent(urlLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(roleLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(passwordLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
        .addComponent(connectButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(httpStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(httpIconStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    getContentPane().add(httpPanel);

    serialPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Timer Connection"));

    serialPanelBody.setLayout(new java.awt.GridLayout(2, 1));

    portList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    portScrollPane.setViewportView(portList);

    serialPanelBody.add(portScrollPane);

    timerClassList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    timerClassScrollPane.setViewportView(timerClassList);

    serialPanelBody.add(timerClassScrollPane);

    scanButton.setText("Stop Scanning");
    scanButton.setToolTipText("");
    scanButton.setEnabled(false);

    serialStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    serialStatusLabel.setText("Scanning for connected timer");

    serialIconStatusPanel.setLayout(new javax.swing.BoxLayout(serialIconStatusPanel, javax.swing.BoxLayout.X_AXIS));

    serialIconStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    serialIconStatus.setPreferredSize(new java.awt.Dimension(60, 60));
    serialIconStatusPanel.add(serialIconStatus);

    javax.swing.GroupLayout serialPanelLayout = new javax.swing.GroupLayout(serialPanel);
    serialPanel.setLayout(serialPanelLayout);
    serialPanelLayout.setHorizontalGroup(
      serialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(serialPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
      .addComponent(serialStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(scanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serialPanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(serialIconStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    serialPanelLayout.setVerticalGroup(
      serialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(serialPanelLayout.createSequentialGroup()
        .addComponent(serialPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scanButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(serialStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(serialIconStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    getContentPane().add(serialPanel);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (false) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Components.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Components.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Components.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Components.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Components().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton connectButton;
  public javax.swing.JLabel httpIconStatus;
  public javax.swing.JPanel httpIconStatusPanel;
  public javax.swing.JPanel httpPanel;
  public javax.swing.JLabel httpStatusLabel;
  public javax.swing.JPasswordField passwordField;
  public javax.swing.JLabel passwordLabel;
  public javax.swing.JList<SerialPortListElement> portList;
  public javax.swing.JScrollPane portScrollPane;
  public javax.swing.JComboBox<String> roleComboBox;
  public javax.swing.JLabel roleLabel;
  public javax.swing.JButton scanButton;
  public javax.swing.JLabel serialIconStatus;
  public javax.swing.JPanel serialIconStatusPanel;
  public javax.swing.JPanel serialPanel;
  public javax.swing.JPanel serialPanelBody;
  public javax.swing.JLabel serialStatusLabel;
  public javax.swing.JList<TimerClassListElement> timerClassList;
  public javax.swing.JScrollPane timerClassScrollPane;
  public javax.swing.JTextField urlField;
  public javax.swing.JLabel urlLabel;
  // End of variables declaration//GEN-END:variables
}
