<?php @session_start();

require_once('inc/data.inc');
require_once('inc/kiosks.inc');
require_once('inc/permissions.inc');
require_once('inc/servername.inc');

if (!isset($_GET['address']) && !isset($_GET['page'])) {
  header('Location: ' . request_path() . '?' .
           http_build_query(array('address' => address_for_current_kiosk())));
  exit();
}

// The award presentation kiosk wants to reset the current award when it starts
// up.
@$_SESSION['permissions'] |= PRESENT_AWARDS_PERMISSION;

session_write_close();


$g_kiosk_parameters_string = '';
function kiosk_parameters() {
  global $g_kiosk_parameters_string;
  return json_decode(empty($g_kiosk_parameters_string) ? '{}' :  $g_kiosk_parameters_string, true);
}

// We're setting $g_kiosk_address here, and then exposing the value in
// javascript generated by kiosk-poller.inc.

// To support testing, user can pass 'page' as a query parameter to name the
// kiosk page they want to see.
if (isset($_GET['page'])) {
  $g_kiosk_address = 'page-param';
  // Confirm the requested page falls under the kiosks directory
  // (Thank you, https://chocapikk.com !)
  $self = dirname(realpath($_SERVER['SCRIPT_FILENAME']));
  $page = realpath($self.'/'.$_GET['page']);
  $kiosks_dir = $self.DIRECTORY_SEPARATOR.'kiosks';
  for ($i = 1; true; ++$i) {
    $dir = dirname($page, $i);
    if ($dir == "/" || $dir == ".") {
      $page = 'kiosks/identify.kiosk';
      break;
    }
    if ($dir == $kiosks_dir) {
      break;
    }
  }
  require($page);
} else {
  $g_kiosk_address = address_for_current_kiosk();
  $kpage = kiosk_page($g_kiosk_address);
  $g_kiosk_parameters_string = $kpage['params'];
  require($kpage['page']);
}
?>
